# 010. PyTorch basic

- GPU check 부분이 있으므로 Google Colab에서 실행

In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt

device = "cuda:0" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [3]:
torch.__version__

'2.7.1+cpu'

## Tensor Data Types

### torch.tensor 함수

`tensor(data, dtype=None, device=None, requires_grad=False) -> Tensor`

     data (array_like): list, tuple, numpy ndarray, scalar, and other types.
     dtype :  `None`인 경우 `data`에서 데이터 유형을 유추합니다.  
     device : `cpu`, `cuda`  
     require_grad(bool, optional): autograd가 작업을 기록해야 하는 경우

Float torch tensor 생성

In [4]:
# numpy array 생성
a = np.ones((2, 3))
# tensor  생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float64 	 torch.float64


In [5]:
# numpy 생성
a = np.ones((2, 3), dtype="float32")
# tensor 생성
b = torch.tensor(a)
# dtype
print(a.dtype, '\t', b.dtype)

float32 	 torch.float32


Integer tensor 생성

In [6]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

In [7]:
# gpu tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.int32, device=device)
x

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

## 1D Tensor Operation

In [8]:
a = torch.tensor([1, 2, 3, 4, 5])

a[0], a[-1]

(tensor(1), tensor(5))

In [9]:
a.size()

torch.Size([5])

In [10]:
a.ndimension()

1

In [11]:
a.view(5, 1)

tensor([[1],
        [2],
        [3],
        [4],
        [5]])

### Tensor Type 변환

- cpu <--> gpu

In [12]:
# cpu tensor
a = a.to(dtype=torch.float32)
a

tensor([1., 2., 3., 4., 5.])

In [13]:
# gpu tensor
b = a.to(device)
b

tensor([1., 2., 3., 4., 5.])

In [ ]:
b = a.cuda()
b

In [15]:
# cpu tensor
d = b.to("cpu")
d

tensor([1., 2., 3., 4., 5.])

### Tensor 생성

- 무작위로 초기화된 행렬 생성 (uniform distribution)

In [16]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0379, 0.4783, 0.4745],
        [0.2974, 0.7954, 0.1890],
        [0.5869, 0.6132, 0.8616],
        [0.8076, 0.6882, 0.3833],
        [0.4293, 0.7113, 0.5927]])


- dtype이 long이고 0으로 채워진 행렬 생성

In [17]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)
print(x.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
torch.int64


- python list로 부터 tensor 생성

In [18]:
a = torch.tensor([7, 4, 3, 2, 6])
a.dtype

torch.int64

In [19]:
b = torch.FloatTensor([7, 4, 3, 2, 6])
b.dtype

torch.float32

In [20]:
a == b

tensor([True, True, True, True, True])

## Tensor 의 shape & dimension (rank)

In [21]:
# 전통정 pytorch 방식
a = torch.Tensor([0, 1, 2, 3, 4])
a.size()

torch.Size([5])

In [22]:
# size() 와 shape 은 alias --> 권장 방식
a.shape

torch.Size([5])

In [23]:
a.ndimension()

1

## reshape
- torch.view : original tensor의 memory 공유 (contiguity 제한)
- torch.reshape: contiguity 제한 없음. 필요에 따라 new tensor 생성. numpy 와 유사한 operation을 위해 기능 제공

In [24]:
print(a)
print(a.view(5, 1))
print(a.reshape(5, 1))

tensor([0., 1., 2., 3., 4.])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.]])


In [25]:
# 4x4 크기의 랜덤한 텐서 생성
x = torch.randn(4, 4)

# x 텐서를 16개의 요소를 가진 1차원 텐서로 변형(view)합니다.
y = x.view(16)
# x 텐서를 2차원 텐서 변형, -1은 나머지 차원의 크기를 자동 계산
# 결과적으로, 이 코드는 x를 2x8 크기의 텐서로 변형합니다.
z = x.view(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [26]:
x = torch.randn(4, 4)
# x 텐서를 16개의 요소를 가진 1차원 텐서로 재구성(reshape).
y = x.reshape(16)

# x 텐서를 -1과 8을 사용하여 2차원 텐서로 재구성
# 결과적으로, 이 코드는 x를 2x8 크기의 텐서로 재구성합니다.
z = x.reshape(-1, 8)

print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [27]:
x = torch.randn(4, 4)
x

tensor([[ 1.7131,  0.8433,  0.0494,  0.8054],
        [ 0.0556,  0.7262, -0.3811,  0.7007],
        [-0.1809,  0.9973,  0.1217,  0.4656],
        [ 0.2320,  0.2599,  0.3887, -0.9441]])

In [28]:
# x 텐서가 연속적인 메모리 레이아웃을 가지고 있는지 확인
# 텐서가 연속적이라면, 메모리 상에서 요소들이 순차적으로 이어져 있음을 의미
x.is_contiguous()

True

In [29]:
# dim0, dim1 을 swap
x.transpose(0, 1)

tensor([[ 1.7131,  0.0556, -0.1809,  0.2320],
        [ 0.8433,  0.7262,  0.9973,  0.2599],
        [ 0.0494, -0.3811,  0.1217,  0.3887],
        [ 0.8054,  0.7007,  0.4656, -0.9441]])

In [30]:
x.transpose(0, 1).is_contiguous()

False

In [31]:
x.transpose(0, 1).reshape(-1, 8)

tensor([[ 1.7131,  0.0556, -0.1809,  0.2320,  0.8433,  0.7262,  0.9973,  0.2599],
        [ 0.0494, -0.3811,  0.1217,  0.3887,  0.8054,  0.7007,  0.4656, -0.9441]])

In [32]:
x.transpose(0, 1).view(-1, 8)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

## numpy 와 tensor 간의 호환성

- memory 를 공유하므로 하나를 수정하면 나머지에 모두 반영  

In [33]:
numpy_array = np.array([0.0, 1.0, 2.0, 3.0, 4.0, 5.0])       # numpy array
torch_tensor = torch.from_numpy(numpy_array)               # torch tensor
torch_tensor

tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64)

In [34]:
back_to_numpy = torch_tensor.numpy()           # numpy array
back_to_numpy

array([0., 1., 2., 3., 4., 5.])

In [35]:
numpy_array, torch_tensor, back_to_numpy

(array([0., 1., 2., 3., 4., 5.]),
 tensor([0., 1., 2., 3., 4., 5.], dtype=torch.float64),
 array([0., 1., 2., 3., 4., 5.]))

In [36]:
back_to_numpy[0] = 100

numpy_array, torch_tensor, back_to_numpy

(array([100.,   1.,   2.,   3.,   4.,   5.]),
 tensor([100.,   1.,   2.,   3.,   4.,   5.], dtype=torch.float64),
 array([100.,   1.,   2.,   3.,   4.,   5.]))

## Scalar value

- 만약 tensor에 하나의 값만 존재한다면, ``.item()`` method를 사용하여 숫자 값을 얻을 수 있습니다.  

In [37]:
x = torch.randn(1)
x.item()

-0.7480030655860901

In [38]:
a = torch.tensor([5., 3., 4., 1.])

print(a[0])
print(a[0].item())

tensor(5.)
5.0


- tensor 가 array 형태인 경우 `numpy()` method 를 통해 ndarray 반환

In [39]:
x = torch.randn(2)
print(x)
print()
print(x.numpy())

tensor([-1.5401,  1.5227])

[-1.5401105  1.522668 ]


## Tensor 의 indexing & slicing

- Python 의 indexing & slicing 과 동일

In [40]:
c = torch.tensor([20, 1, 2, 3, 4])
c[0] = 100
c[4] = 0
c, c.dtype

(tensor([100,   1,   2,   3,   0]), torch.int64)

In [41]:
d = c[1:4]
d

tensor([1, 2, 3])

In [42]:
c[3:5] = torch.tensor([300.0, 400.0])
c

tensor([100,   1,   2, 300, 400])

## Basic Operations - numpy 와 동일

In [43]:
# element-wise 덧셈, 뺄셈
u = torch.tensor([1.0, 0.0])
v = torch.tensor([0.0, 1.0])
z = u + v
z

tensor([1., 1.])

In [44]:
z = u - v
z

tensor([ 1., -1.])

In [45]:
# element-wise 곱셈
u = torch.tensor([1, 2])
v = torch.tensor([3, 2])
z = u * v
z

tensor([3, 4])

In [46]:
# 스칼라 곱
y = torch.tensor([1, 2])
z = 2 * y
z

tensor([2, 4])

In [47]:
# dot product
u = torch.tensor([1, 2])
v = torch.tensor([3, 1])
result = torch.dot(u, v)
result

tensor(5)

## 기타

In [48]:
# broadcasting
u = torch.tensor([1, 2, 3, -1])
z = u + 1
z

tensor([2, 3, 4, 0])

In [49]:
# mean, max, Standard Deviation
a = torch.tensor([1, -2, 3, 4, 5], dtype=torch.float32)

a.mean(), a.max(), a.std()

(tensor(2.2000), tensor(5.), tensor(2.7749))

## torch.linspace 와 np.linspace 비교

In [50]:
np_linspace = np.linspace(-2, 2, 5)
np_linspace

array([-2., -1.,  0.,  1.,  2.])

In [51]:
torch_linspace = torch.linspace(-2, 2, 5)
torch_linspace

tensor([-2., -1.,  0.,  1.,  2.])

In [52]:
torch.linspace(10, 20, 10)

tensor([10.0000, 11.1111, 12.2222, 13.3333, 14.4444, 15.5556, 16.6667, 17.7778,
        18.8889, 20.0000])

## torch.arange 와 np.arange 비교

In [53]:
np.arange(-100, 100, 0.1)

array([-100. ,  -99.9,  -99.8, ...,   99.7,   99.8,   99.9], shape=(2000,))

In [54]:
torch.arange(-100, 100, 0.1)

tensor([-100.0000,  -99.9000,  -99.8000,  ...,   99.7000,   99.8000,
          99.9000])

## 2D Tensor Operation

In [55]:
_2d_tensor = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33], [41, 42, 43]])
_2d_tensor

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])

- ndimension  
- shape  
- size()  
- numel (number of elements)

In [56]:
print(_2d_tensor)
print(_2d_tensor.ndimension())
print(_2d_tensor.shape)
print(_2d_tensor.size())
print(_2d_tensor.numel())

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33],
        [41, 42, 43]])
2
torch.Size([4, 3])
torch.Size([4, 3])
12


## matrix 간의 연산

In [57]:
x = torch.tensor([[1, 0], [0, 1]])
y = torch.tensor([[2, 1], [1, 2]])
print(x)
print(y)

tensor([[1, 0],
        [0, 1]])
tensor([[2, 1],
        [1, 2]])


- element-wise 연산

In [58]:
x * y

tensor([[2, 0],
        [0, 2]])

## matrix multiplication

In [59]:
x = torch.tensor([[0, 1, 1], [1, 0, 1]])
y = torch.tensor([[1, 1], [1, 1], [-1, 1]])

print(x)
print(y)

tensor([[0, 1, 1],
        [1, 0, 1]])
tensor([[ 1,  1],
        [ 1,  1],
        [-1,  1]])


In [60]:
torch.mm(x, y)

tensor([[0, 2],
        [0, 2]])

In [61]:
np.matmul(x.numpy(), y.numpy())

array([[0, 2],
       [0, 2]])

### Concatenation

- default - first axis(row-wise)로 concatenate
- column-wise로 concatenate 하려면 axis=1 로 지정

In [62]:
x_1 = torch.tensor([[1, 2, 3], [4, 5, 6]])
x_2 = torch.tensor([[7, 8, 9], [10, 11, 12]])
print(x_1)
print(x_2)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[ 7,  8,  9],
        [10, 11, 12]])


In [63]:
torch.cat([x_1, x_2])

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [64]:
torch.cat([x_1, x_2], axis=1)

tensor([[ 1,  2,  3,  7,  8,  9],
        [ 4,  5,  6, 10, 11, 12]])

### torch.sum, torch.max, torch.min, torch.argmax, torch.argmin

- torch.sum(input, dim, keepdim=False, dtype=None) → Tensor  
주어진 차원 dim에서 입력 텐서의 각 행의 합(max, min)을 반환합니다.

- dim 을 지정한 경우, 지정된 dim을 축소하는 것입니다. 따라서 dim 0(행)을 접으면 하나의 행이 됩니다(열 단위로 합산).

In [65]:
x = torch.tensor([
     [1, 2, 3],
     [4, 5, 6]
   ])
x.shape

torch.Size([2, 3])

In [66]:
torch.sum(x)

tensor(21)

In [67]:
torch.sum(x, dim=0)

tensor([5, 7, 9])

In [68]:
torch.sum(x, dim=1)

tensor([ 6, 15])

In [69]:
torch.max(x, axis=0), torch.min(x, axis=0)

(torch.return_types.max(
 values=tensor([4, 5, 6]),
 indices=tensor([1, 1, 1])),
 torch.return_types.min(
 values=tensor([1, 2, 3]),
 indices=tensor([0, 0, 0])))

In [70]:
torch.max(x, axis=1), torch.min(x, axis=1)

(torch.return_types.max(
 values=tensor([3, 6]),
 indices=tensor([2, 2])),
 torch.return_types.min(
 values=tensor([1, 4]),
 indices=tensor([0, 0])))

In [71]:
torch.argmax(x), torch.argmin(x)

(tensor(5), tensor(0))

In [72]:
torch.argmax(x, axis=0), torch.argmin(x, axis=0)

(tensor([1, 1, 1]), tensor([0, 0, 0]))

In [73]:
torch.argmax(x, axis=1), torch.argmin(x, axis=1)

(tensor([2, 2]), tensor([0, 0]))